In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

# 1. MOST VIEWED VIDEOS ON YOUTUBE FROM WIKIPEDIA.COM

In [1]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

Rank=[]
Name=[]
Artist=[]
Views=[]
Uploaddate=[]

In [2]:
driver=webdriver.Chrome(r"C:\Users\Harshil Goradia\Downloads\chromedriver_win32\chromedriver")
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [3]:
rows= WebDriverWait(driver, 20).until(EC.visibility_of_all_elements_located((By.XPATH, "//table[@class='wikitable sortable jquery-tablesorter']/tbody//tr")))
for row in rows:
    Rank.append(row.find_element_by_xpath('./td[1]').text)
    Name.append(row.find_element_by_xpath('./td[2]').text)
    Artist.append(row.find_element_by_xpath('./td[3]').text)
    Views.append(row.find_element_by_xpath('./td[4]').text)
    Uploaddate.append(row.find_element_by_xpath('./td[5]').text)
    
driver.close()

In [6]:
df=pd.DataFrame({"Rank":Rank[:30],"Name":Name[:30],"Artist":Artist[:30],"Views":Views[:30],"Upload Date":Uploaddate[:30]})
df

,Rank,Name,Artist,Views,Upload Date
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,8.96,"June 17, 2016"
1,2.,"""Despacito""[24]",Luis Fonsi,7.44,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,5.55,"October 8, 2016"
3,4.,"""Shape of You""[26]",Ed Sheeran,5.38,"January 30, 2017"
4,5.,"""See You Again""[27]",Wiz Khalifa,5.18,"April 6, 2015"
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.44,"January 31, 2012"
6,7.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,4.31,"May 2, 2018"
7,8.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,4.26,"February 27, 2018"
8,9.,"""Uptown Funk""[33]",Mark Ronson,4.23,"November 19, 2014"
9,10.,"""Gangnam Style""[34]",Psy,4.12,"July 15, 2012"
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,3.99,"March 6, 2014"
11,12.,"""Sugar""[37]",Maroon 5,3.51,"January 14, 2015"
12,13.,"""Dame Tu Cosita""[38]",El Chombo,3.46,"April 5, 2018"
13,14.,"""Sorry""[39]",Justin Bieber,3.45,"October 22, 2015"
14,15.,"""Roar""[40]",Katy Perry,3.39,"September 5, 2013"
15,16.,"""Counting Stars""[41]",OneRepublic,3.34,"May 31, 2013"
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.29,"October 7, 2014"
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,3.15,"May 24, 2018"
18,19.,"""Dark Horse""[44]",Katy Perry,3.10,"February 20, 2014"
19,20.,"""Faded""[45]",Alan Walker,3.10,"December 3, 2015"
20,21.,"""Shake It Off""[46]",Taylor Swift,3.07,"August 18, 2014"
21,22.,"""Girls Like You""[47]",Maroon 5,3.07,"May 31, 2018"
22,23.,"""Lean On""[48]",Major Lazer,3.06,"March 22, 2015"
23,24.,"""Bailando""[49]",Enrique Iglesias,3.06,"April 11, 2014"
24,25.,"""Let Her Go""[50]",Passenger,3.03,"July 25, 2012"
25,26.,"""Mi Gente""[51]",J Balvin,2.94,"June 29, 2017"
26,27.,"""Perfect""[52]",Ed Sheeran,2.90,"November 9, 2017"
27,28.,"""Waka Waka (This Time for Africa)""[53]",Shakira,2.88,"June 4, 2010"
28,29.,"""Axel F""[54]",Crazy Frog,2.88,"June 16, 2009"
29,30.,"""Hello""[55]",Adele,2.85,"October 22, 2015"

# 2. TEAM INDIA'S FIXTURES FROM BCCI.TV

In [6]:
Url = "https://www.bcci.tv/"
driver.get(Url)
time.sleep(3)

In [11]:
int_btn=driver.find_elements_by_xpath("//li[@class='footer-navigation__item footer-navigation__item--secondary']")
int_btn

[<selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="f728179d-dd14-40cb-921a-163ce99346af")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="7b43b5de-ae71-4128-8387-467869efda5e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="c4634135-583a-4c20-8f4c-a4655bf0b502")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="08950f3c-eca4-4e32-aab8-ab6e7536e6bd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="794b3c49-9595-44da-867d-d6a7ccec5222")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="a5caf47c-51d0-4533-9a5c-3152dffe6d22")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="a29b45d5-9279-46b1-92b7-9636008b4d89")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="8ca6a3e9-8b9d-4dd1-955e-1a6855de0ddb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="21e47dac-4df1-4b94-b656-73f00ae89a2c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="41bafb31-75e8-47c1-a25d-118fb6333bfd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="91817500-9cc2-46a1-b74f-52bc7c1f958d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="a783705b-b514-4cdf-885f-94f8a5f4c8c7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="92fbbce4-f4f6-41b5-bdc1-1531c1047f73")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="4136bbbf-aa35-44b0-88c5-10465f1ec1db")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="131d0473-6521-4a3d-9857-de3f45f64c7a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="ce6ec34f-eb1d-41a1-a27c-0806900cc45a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="8830911d-80ac-44c0-ada8-6a8afa7bc08d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="ef076a2a-74cb-47d0-9ce4-144ac52893d9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="31a9e846-bbaa-4f03-b578-7c4dfd038e69")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="faec22b5-2480-4962-aab7-b720d41d943c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="72a3cb91-1a9a-4691-b9e7-86dfd6854d23")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="51b5ccf5-1779-4214-97e2-ca2f05019348")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="057d4669-a081-4c92-8a93-30053fe4abea")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="07e36454-6270-44de-90d2-062f8713f0c4")>]

In [13]:
for i in int_btn:
    if i.text == "Fixtures":
        i.click()
        break

In [14]:
series=driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']")
series

[<selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="7676cd60-6bcd-4503-8f01-8aff14530e07")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="533b53ed-bb1c-4af1-b078-beb4276ba6dd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="d8d11901-7b7d-456d-9a6c-72750c9254e6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="b4510f9b-4888-4eb1-b1e8-cc518a731ea4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="faad94da-38be-4766-b25f-e66d844a197b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="bee4f65b-e1d9-4bb9-9e71-7335eccf0dba")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="18320253-038f-43be-9ea3-ed9a1f004144")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="4452d080-0721-47da-b017-ae84e425d041")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="f35dd60c-d2c9-4070-b7e7-264da9cc9c38")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="3f4c493b-b844-45c0-b620-15645ce40d4f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="2d376da4-46fd-4008-99d5-80492cdbe620")>]

In [15]:
Series=[]
for i in series:
    if i.text is None:
        Series.append('Not')
    else:
        Series.append(i.text)
        
Series

['SRI LANKA V INDIA 2021',
 'SRI LANKA V INDIA 2021',
 'SRI LANKA V INDIA 2021',
 'SRI LANKA V INDIA 2021',
 'SRI LANKA V INDIA 2021',
 'SRI LANKA V INDIA 2021',
 'ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021',
 'ENGLAND V INDIA 2021']

In [16]:
match=driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
match

[<selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="1c781874-3c79-4c42-a4ca-c196743c9e3b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="03f4f022-6ba9-42c0-ad8b-34b309f39ae0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="f20e7c19-8279-47b4-82b0-93314205eecf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="bf054f21-c7db-45a3-9cd3-2eeeaaeedfe8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="05df0172-970e-43c3-b0f6-2547531107d7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="11d15ce6-2075-4144-b9d5-11a690335355")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="83413f6e-736a-40dc-8251-b0158e07bdf0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="691835a5-7dc0-4337-9f1f-0ff751c5c140")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="31e520b3-41f8-4492-b2fa-62716a1444a6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="84b022b7-aa13-4816-8415-fc6d2260af7f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="22805058-47a0-414c-abac-cdad06807f3d")>]

In [17]:
Match=[]
for i in match:
    if i.text is None:
        Match.append('Not')
    else:
        Match.append(i.text)
        
Match

['1st ODI',
 '2nd ODI',
 '3rd ODI',
 '1st T20I',
 '2nd T20I',
 '3rd T20I',
 '1st Test',
 '2nd Test',
 '3rd Test',
 '4th Test',
 '5th Test']

In [18]:
stadium=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
stadium

[<selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="88c40a58-c24c-43d5-88a8-649ed11bc7e6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="06e7ac77-aef7-4706-965d-c793ac8cda0e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="293256ee-d070-4230-8b2b-59596582577b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="bfceb2ab-74db-439e-9a39-46484d87329c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="849ba15e-9cca-4f4a-9494-f97407737256")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="3dbff01e-14b4-4d3f-b51d-3179f8ff3f21")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="a5d4a878-220c-4168-ab0a-2e46bed7129f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="d4b84d6d-3122-4e58-8978-88f38bfd34e8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="a04b12e1-be8a-4497-aa88-d0a9c9b69089")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="f603357a-438a-46f9-b270-e5ebdf21def3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="c966119cf3d7e92dea7cf879f54a04a9", element="7b5b2744-a732-44da-81ae-64df06354ee2")>]

In [19]:
Place=[]
for i in stadium:
    if i.text is None:
        Place.append('Not')
    else:
        Place.append(i.text)
        
Place

['R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'Trent Bridge, Nottingham',
 "Lord's, London",
 'Headingley, Leeds',
 'The Oval, London',
 'Old Trafford, Manchester']

In [25]:
date=driver.find_elements_by_xpath("//span[@class='fixture__date']")
month=driver.find_elements_by_xpath("//span[@class='fixture__month']")
time=driver.find_elements_by_xpath("//span[@class='fixture__time']")

Date=[]
Month=[]
Time=[]

for i in date:
    if i.text is None:
        Date.append('Not')
    else:
        Date.append(i.text)
        
for i in month:
    if i.text is None:
        Month.append('Not')
    else:
        Month.append(i.text)        
        
for i in time:
    if i.text is None:
        Time.append('Not')
    else:
        Time.append(i.text)

In [26]:
Fixtures=pd.DataFrame({})
Fixtures['Series']=Series
Fixtures['Match']=Match
Fixtures['Place']=Place
Fixtures['Date']=Date
Fixtures['Month']=Month
Fixtures['Time']=Time

Fixtures

,Series,Match,Place,Date,Month,Time
0,SRI LANKA V INDIA 2021,1st ODI,"R Premadasa Stadium, Colombo",13,JULY,14:30 IST
1,SRI LANKA V INDIA 2021,2nd ODI,"R Premadasa Stadium, Colombo",16,JULY,14:30 IST
2,SRI LANKA V INDIA 2021,3rd ODI,"R Premadasa Stadium, Colombo",18,JULY,14:30 IST
3,SRI LANKA V INDIA 2021,1st T20I,"R Premadasa Stadium, Colombo",21,JULY,19:00 IST
4,SRI LANKA V INDIA 2021,2nd T20I,"R Premadasa Stadium, Colombo",23,JULY,19:00 IST
5,SRI LANKA V INDIA 2021,3rd T20I,"R Premadasa Stadium, Colombo",25,JULY,19:00 IST
6,ENGLAND V INDIA 2021,1st Test,"Trent Bridge, Nottingham",04,AUGUST,15:30 IST
7,ENGLAND V INDIA 2021,2nd Test,"Lord's, London",12,AUGUST,15:30 IST
8,ENGLAND V INDIA 2021,3rd Test,"Headingley, Leeds",25,AUGUST,15:30 IST
9,ENGLAND V INDIA 2021,4th Test,"The Oval, London",02,SEPTEMBER,15:30 IST
10,ENGLAND V INDIA 2021,5th Test,"Old Trafford, Manchester",10,SEPTEMBER,15:30 IST

# 3. SELENIUM EXCEPTION FROM GURU99.COM

In [7]:
driver=webdriver.Chrome(r"C:\Users\Harshil Goradia\Downloads\chromedriver_win32\chromedriver")
driver.get('https://www.guru99.com/')

Exception=[]
Description=[]

In [8]:
sln_btn=driver.find_elements_by_xpath("//li[@class='fa fa-chevron-circle-right']/a")
for i in sln_btn:
    if i.text == "Selenium":
        i.click()
        break

In [9]:
btn=driver.find_element_by_xpath("//a[@href='/exception-handling-selenium.html']")
btn

In [10]:
btn=driver.find_element_by_xpath("//a[@href='/exception-handling-selenium.html']")
btn.click()

In [11]:
rows= WebDriverWait(driver, 20).until(EC.visibility_of_all_elements_located((By.XPATH, "//table[@class='table table-striped']/tbody//tr")))
for row in rows:
    Exception.append(row.find_element_by_xpath('./td[1]').text)
    Description.append(row.find_element_by_xpath('./td[2]').text)

In [13]:
Exception_df=pd.DataFrame({'Exception Name': Exception[1:],"Description": Description[1:]})
Exception_df

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4. STATE WISE GDP OF INDIA

In [14]:
driver=webdriver.Chrome(r"C:\Users\Harshil Goradia\Downloads\chromedriver_win32\chromedriver")
driver.get('http://statisticstimes.com/')

In [16]:
btnn=driver.find_elements_by_xpath("//button[@class='dropbtn']")
for i in btnn:
    if i.text =='Economy':
        i.click()
        break

In [17]:
btnn1=driver.find_elements_by_xpath("//a[@href='economy/india-statistics.php']")
for i in btnn1:
    if i.text == "India":
        i.click()
        break

In [18]:
statesbtn=driver.find_elements_by_tag_name('li')
for i in statesbtn:
    if i.text == "» GDP of Indian states":
        i.click()
        break

In [19]:
Rank=[]
State=[]
GSDP_1920=[]
GSDP_1819=[]
Share_1819=[]
GDP=[]

In [21]:
rows= WebDriverWait(driver, 20).until(EC.visibility_of_all_elements_located((By.XPATH, "//table[@class='display dataTable']/tbody//tr")))
for row in rows:
    Rank.append(row.find_element_by_xpath('./td[1]').text)
    State.append(row.find_element_by_xpath('./td[2]').text)
    GSDP_1920.append(row.find_element_by_xpath('./td[3]').text)
    GSDP_1819.append(row.find_element_by_xpath('./td[4]').text)
    Share_1819.append(row.find_element_by_xpath('./td[5]').text)
    GDP.append(row.find_element_by_xpath('./td[6]').text)

In [26]:
State_GDP=pd.DataFrame({"Rank":Rank[:33],"State":State[:33],"GSDP 19-20":GSDP_1920[:33],"GSDP 18-19":GSDP_1819[:33],"Share 18-19":Share_1819[:33],"GDP($billion)":GDP[:33]})
State_GDP

,Rank,State,GSDP 19-20,GSDP 18-19,Share 18-19,GDP($billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5. GITHUB TRENDING REPOSITORIES

In [14]:
driver=webdriver.Chrome(r"C:\Users\Harshil Goradia\Downloads\chromedriver_win32\chromedriver")

In [15]:
Url = "https://github.com/"
driver.get(Url)

In [18]:
search_btn=driver.find_elements_by_xpath("//details[@class='HeaderMenu-details details-overlay details-reset width-full']//summary")
for i in search_btn:
    if i.text == 'Explore':
        i.click()
        break

In [19]:
btn=driver.find_elements_by_xpath("//li[@class='edge-item-fix']/a")
for i in btn:
    if i.text == 'Trending':
        i.click()
        break

In [20]:
urls=[]
for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
    urls.append(i.get_attribute("href"))

In [21]:
len(urls)

25

In [22]:
name1=[]
desc1=[]
contri1=[]
lang1=[]

In [25]:
for i in urls:
    driver.get(i)
    time.sleep(3)
    
    try:
        name_1=driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']/a")
        name1.append(name_1.text)
    except NoSuchElementException:
        name1.append('-')
        
        
    try:
        desc_1=driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        desc1.append(desc_1.text)
    except NoSuchElementException:    
        desc1.append('-')
        
        
    try:
        contri_1=driver.find_element_by_xpath("//div[@class='BorderGrid-cell']/h2/a/span")
        contri1.append(contri_1.text)
    except NoSuchElementException:
        contri1.append('-')
        
     
    try:
        lang_1=driver.find_element_by_xpath("//ul[@class='list-style-none']/li/a/span")
        lang1.append(lang_1.text)
    except NoSuchElementException:
        lang1.append('-')

In [26]:
Github1=pd.DataFrame({})
Github1['Name']=name1
Github1['Description']=desc1
Github1['Contibutors']=contri1
Github1['Language Used']=lang1


Github1

,Name,Description,Contibutors,Language Used
0,javascript-algorithms,📝 Algorithms and data structures implemented i...,,JavaScript
1,PayloadsAllTheThings,A list of useful payloads and bypass for Web A...,3,Python
2,IoT-For-Beginners,"12 Weeks, 24 Lessons, IoT for All!",22,C++
3,30-seconds-of-code,Short JavaScript code snippets for all your de...,258,JavaScript
4,Anime-Girls-Holding-Programming-Books,Anime Girls Holding Programming Books,,-
5,javascript,JavaScript Style Guide,,JavaScript
6,imgui,Dear ImGui: Bloat-free Graphical User interfac...,72,C++
7,faker2,不知名大佬备份,,JavaScript
8,project-guidelines,A set of best practices for JavaScript projects,,JavaScript
9,clean-code-javascript,🛁 Clean Code concepts adapted for JavaScript,,JavaScript
10,javascript-questions,A long list of (advanced) JavaScript questions...,,-
11,javascript-algorithms,📝 Algorithms and data structures implemented i...,,JavaScript
12,PayloadsAllTheThings,A list of useful payloads and bypass for Web A...,3,Python
13,IoT-For-Beginners,"12 Weeks, 24 Lessons, IoT for All!",22,C++
14,30-seconds-of-code,Short JavaScript code snippets for all your de...,258,JavaScript
15,Anime-Girls-Holding-Programming-Books,Anime Girls Holding Programming Books,,-
16,javascript,JavaScript Style Guide,,JavaScript
17,imgui,Dear ImGui: Bloat-free Graphical User interfac...,72,C++
18,faker2,不知名大佬备份,,JavaScript
19,project-guidelines,A set of best practices for JavaScript projects,,JavaScript
20,clean-code-javascript,🛁 Clean Code concepts adapted for JavaScript,,JavaScript
21,javascript-questions,A long list of (advanced) JavaScript questions...,,-
22,nodebestpractices,✅ The Node.js best practices list (June 2021),196,JavaScript
23,awesome-javascript,🐢 A collection of awesome browser-side JavaScr...,,-
24,algorithm-base,专门为刚开始刷题的同学准备的算法基地，没有最细只有更细，立志用动画将晦涩难懂的算法说的通俗易懂！,,Java
25,system-design-primer,Learn how to design large-scale systems. Prep ...,,Python
26,go-recipes,Handy commands to run in Go projects,3,-
27,sodium-fabric,A Fabric mod designed to improve frame rates a...,3,Java
28,free-programming-books,📚 Freely available programming books,"1,626",-
29,alias-free-gan-pytorch,Unofficial implementation of Alias-Free Genera...,,Python
30,eattheblocks,"Source code for Eat The Blocks, a screencast f...",,JavaScript
31,flutter_ecommerce_app,E-Commerce App built in flutter,1,Dart
32,youtube-dl,Command-line program to download videos from Y...,"1,118",Python
33,Magisk,The Magic Mask for Android,119,C++
34,godot,Godot Engine – Multi-platform 2D and 3D game e...,32,C++
35,Incident-Playbook,GOAL: Incident Response Playbooks Mapped to MI...,3,Python

# 6. BILLBOARDS HOT 100

In [27]:
Url = "https://www.billboard.com/"
driver.get(Url)

In [62]:
search_charts=driver.find_elements_by_xpath("//ul[@class='header__link-list header__main-menu bg--dark']/li/a")
search_charts

[<selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="a798bfe9-3ef9-4b76-b86e-3a762103f6cb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="7e757307-4ddf-402e-a39c-9105722bfb3a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="eff00797-7ba6-47a7-8503-737bd05da50e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="c9f963a6-4b51-44ff-b6d3-f97e603b5533")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="40b81cd9-85d0-4cb2-9459-07c4fe0c50d5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="8f030811-ffa5-4e7f-9bca-01251b12bb65")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="8045e7e4-f981-49d1-a69c-ecf14fbd91e5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="a344c573-0e82-4487-bcde-b068a79d4d1b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="4614574c-3366-4778-97d2-916c6a319958")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="b53a844b-1de6-46ae-b164-cb2644768fca")>,
 <selenium.webdriver.remote.webelement.WebElement (session="717176d1a0f69cc98bf716b694abdd08", element="57c3305e-6461-4b7d-b8f6-7b7e92852327")>]

In [63]:
for i in search_charts:
    if i.text == 'CHARTS':
        i.click()
        break

In [56]:
for i in search_charts:
    if i.text == 'Charts':
        i.click()
        break

In [66]:
search_hot=driver.find_element_by_xpath("//div[@class='charts-landing__info--top charts-landing__info--top--hot-100']")
search_hot

In [67]:
search_hot=driver.find_element_by_xpath("//div[@class='charts-landing__info--top charts-landing__info--top--hot-100']")
search_hot.click()

In [74]:
song=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
artist=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
last_Week=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
peak=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
weeks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")

In [77]:
Song=[]
for i in song:
    if i.text is None:
        Song.append('-')
    else:
        Song.append(i.text) 
        
Artists=[]        
for i in artist:
    if i.text is None:
        Artists.append('-')
    else:
        Artists.append(i.text) 
        
Last_Week=[]        
for i in last_Week:
    if i.text is None:
        Last_Week.append('-')
    else:
        Last_Week.append(i.text) 
        
Peak=[]        
for i in peak:
    if i.text is None:
        Peak.append('-')
    else:
        Peak.append(i.text) 
        
Weeks=[]        
for i in weeks:
    if i.text is None:
        Weeks.append('-')
    else:
        Weeks.append(i.text)

In [78]:
Billboard100=pd.DataFrame({})
Billboard100['Song Name']=Song
Billboard100['Artist Name']=Artists
Billboard100['Last Week Ranking']=Last_Week
Billboard100['Peak']=Peak
Billboard100['Weeks on Charts']=Weeks

Billboard100

,Song Name,Artist Name,Last Week Ranking,Peak,Weeks on Charts
0,Butter,BTS,1,1,7
1,Good 4 U,Olivia Rodrigo,2,1,8
2,Levitating,Dua Lipa Featuring DaBaby,4,2,40
3,Kiss Me More,Doja Cat Featuring SZA,3,3,13
4,Montero (Call Me By Your Name),Lil Nas X,8,1,15
...,...,...,...,...,...
95,All I Know So Far,P!nk,-,74,4
96,What's Next,Drake,-,1,16
97,Enough For You,Olivia Rodrigo,-,14,6
98,Juggernaut,"Tyler, The Creator Featuring Lil Uzi Vert & Ph...",40,40,2
99,Tell Em,Cochise & $NOT,-,64,4

# 7. NAUKRI.COM RECRUITERS

In [82]:
driver=webdriver.Chrome(r"C:\Users\Harshil Goradia\Downloads\chromedriver_win32\chromedriver")

In [83]:
Url = "https://www.naukri.com/"
driver.get(Url)

In [84]:
rec_btn=driver.find_element_by_xpath("//a[@title='Search Recruiters']")

In [85]:
driver.get(rec_btn.get_attribute('href'))

In [86]:
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")

In [87]:
btn=driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")

In [88]:
btn.click()

In [89]:
name=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
desig=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
skills=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
company=driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")

In [90]:
Name=[]
Designation=[]
Location=[]
Skills=[]
Company=[]

for i in name:
    if i.text is None:
        Name.append("-")
    else:
        Name.append(i.text)

for i in desig:
    if i.text is None:
        Desgination.append("-")
    else:
        Designation.append(i.text)  
    
for i in skills:
    if i.text is None:
        Skills.append("-")
    else:
        Skills.append(i.text)
        
for i in company:
    if i.text is None:
        Company.append("-")
    else:
        Company.append(i.text)

In [91]:
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='ellipsis'][1]"):
    urls.append(i.get_attribute("href"))

In [92]:
for i in urls:
    driver.get(i)
    time.sleep(3)
        

    try:
        location=driver.find_element_by_xpath("//div[@class='oh'][2]/a[1]")
        Location.append(location.text)
    except NoSuchElementException:
        Location.append('-')

In [93]:
Recruiters=pd.DataFrame({"Name":Name,"Company":Company,"Designation":Designation,"Skills they hire for":Skills,"Location":Location})        
Recruiters

,Name,Company,Designation,Skills they hire for,Location
0,Aakash Harit,Data Science Network,HR Manager,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Shore Infotech India Pvt. Ltd,Company Recruiter,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,MARSIAN Technologies LLP,Company HR,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Enerlytics Software Solutions Pvt Ltd,Company Recruiter,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,LibraryXProject,Founder CEO,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Apidel Technologies Division of Transpower,Recruitment Lead Consultant,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,IFMR,Programme Manager,Data Science,Chennai
7,Balu Ramesh,Techvantage Systems Pvt Ltd,HR Administrator,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Weupskill- Live Wire India,Director,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,CBL Data Science Private Limited,Human Resource,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Innominds Software,Executive Hiring,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,MoneyTap,Company HR,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,QuantMagnum Technologies Pvt. Ltd.,Company HR,"Office Administration, Hr Administration, tele...",Mumbai
13,Ruchi Dhote,Bristlecone India Ltd,Senior Executive Talent Acquisition,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
14,Mahesh Babu Channa,SocialPrachar.com,HR Team Lead,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Kapil Devang,BISP Solutions,HR Manager,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Manisha Yadav,Easi Tax,HR Executive,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
17,Riya Rajesh,Novelworx Digital Solutions,Manager Talent Acquisition,Data Science,Cochin
18,Rashmi Bhattacharjee,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,HR Head,"Corporate Sales, Software Development, Softwar...",Delhi
19,Faizan Kareem,FirstTech Consaltants Pvt.Ltd,HR MANAGER,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
20,Rithika dadwal,Affine Analytics,HR Recruiter,"Data Science, Machine Learning, Python, R, Dee...",Pune
21,Azahar Shaikh,NEAL ANALYTICS SERVICES PVT LTD,Company Recruiter,"Data Science, Artificial Intelligence, Machine...",Pune
22,Sandhya Khandagale,Compumatrice Multimedia Pvt Ltd,HR Recruiter,"Big Data, Data Science, Artificial Intelligenc...",Pune
23,Shaun Rao,Exela Technologies,Manager Human Resources,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
24,Manas,Autumn Leaf Consulting Services Private...,Lead Talent acquisition,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
25,kumar,trainin,Proprietor,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
26,Sunil Vedula,Nanoprecise Sci Corp,CEO,"Signal Processing, Machine Learning, Neural Ne...",Others
27,Rajat Kumar,R.S Consultancy &amp; Services,Founder CEO,"Web Technologies, Project Management, Software...",Delhi
28,Priya Khare,Independent Consultant,Senior Manager,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
29,Dhruv Dev Dubey,Confidential,Company Recruitment Head,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
30,Jayanth N,"Dollarbird Information Services Pvt, Ltd",Project Manager,"Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
31,Radha Manivasagam,Techcovery,HR Executive,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
32,Ravi Dubey,HyrEzy Talent Solutions LLP,Recruitment Manager,Walmart Interra Skeps Expressstores indifi whi...,Ghaziabad
33,Prateek Kumar,Trisect,Head,"Java, Python, Angularjs, Software Testing, Mac...",Noida
34,Amit Sharma,ASCO consulting,Consultant,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
35,Kanan,NY INST,senior technology instructor,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
36,Shashikant Chaudhary,3D India Staffing Research &amp; Consulting...,HR Recruiter/HR Excutive,"Relationship Management, Retail Sales, Private...",Aligarh
37,Brad,O.C. Tanner,"Manager, Technical Recruiting","Data Science, Software Engineering",Salt Lake City
38,Rutuja Pawar,Demand Matrix,Technical Recruiter,"Data Science, Big Data Analytics, Digital Mark...",Pune
39,Madhusudhan Sridhar,MADHUSUDHAN SRIDHAR,Erp Implementer,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
40,Ankit Sinha,Suntech Global,Head Analytics,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
41,Gaurav Chouhan,Strategic Consulting Lab,Chief Technical Officer,"Software Development, Business Intelligence, B...",Indore
42,Rashi Kacker,Impel Labs Pvt. Ltd.,Sr Product Manager,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
43,Ashwini,MRP Advisers,Director Global Delivery,"Data Science, Media Marketing, Resource Planni...",MYSORE
44,Balaji Kolli,Saras Solutions India Pvt Ltd,Co Founder,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
45,Rajani Nagaraj,WildJasmine,HR Manager,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
46,ROHIT Kumar,LNT Private Limited,Architect,"Software Development, Core Java, Unit Testing,...",Mumbai
47,Amir Chowdhury,Granular.ai,Managing Partner,"Machine Learning, Data Science, Product Manage...",
48,Shailja Mishra,Certybox Pvt.Ltd.,HR Manager,"consulting, Education Counseling, Educational ...",Noida
49,Sunny Sharma,Western Service Providers,Managing Director - HR,"Software Professionals, Engineering, Technical...",Mumbai

# 8. THEGUARDIAN.COM TOP 100 BOOKS

In [16]:
driver=webdriver.Chrome(r"C:\Users\Harshil Goradia\Downloads\chromedriver_win32\chromedriver")
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')

In [17]:
Book=[]
Author=[]
Volumes_sold=[]
Publisher=[]
Genre=[]

In [20]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

rows= WebDriverWait(driver, 20).until(EC.visibility_of_all_elements_located((By.XPATH, "//table[@class='in-article sortable']/tbody//tr")))
for row in rows:
    Book.append(row.find_element_by_xpath('./td[2]').text)
    Author.append(row.find_element_by_xpath('./td[3]').text)
    Volumes_sold.append(row.find_element_by_xpath('./td[4]').text)
    Publisher.append(row.find_element_by_xpath('./td[5]').text)
    Genre.append(row.find_element_by_xpath('./td[6]').text)

In [21]:
Top100Books=pd.DataFrame({"Book Name":Book,"Author Name":Author,"Volumes Sold":Volumes_sold,"Publisher":Publisher,"Genre":Genre})
Top100Books

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. IMDB TOP 100

In [143]:
 Url = "https://www.imdb.com/list/ls095964455/"
driver.get(Url)

In [144]:
name=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")

In [146]:
Name=[]
for i in name:
    if i.text is None:
        Name.append("-")
    else:
        Name.append(i.text)
Name

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [147]:
span=driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
Span=[]
for i in span:
    if i.text is None:
        Span.append("-")
    else:
        Span.append(i.text)
Span

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014– )',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011– )',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016– )',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016– )',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2021)',
 '(2015– )',
 '(1999–2022)',
 '(2013– )',
 '(2004–2010)',
 '(2013– )',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016– )',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2022)',
 '(2013–2015)',
 '(2019– )',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015– )',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017– )',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005–2020)',
 '(2015–2019)',
 '(2018)']

In [197]:
runtime=driver.find_elements_by_xpath("//span[@class='runtime']")
genre=driver.find_elements_by_xpath("//span[@class='genre']")
rating=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']")
vote=driver.find_elements_by_name("nv")

In [198]:
Runtime=[]
Genre=[]
Rating=[]
Votes=[]

In [199]:
for i in runtime:
    if i.text is None:
        Runtime.append("-")
    else:
        Runtime.append(i.text)
        
        

for i in genre:
    if i.text is None:
        Genre.append("-")
    else:
        Genre.append(i.text)        
        
        

for i in rating:
    if i.text is None:
        Rating.append("-")
    else:
        Rating.append(i.text)    


for i in vote:
    if i.text is None:
        Votes.append("-")
    else:
        Votes.append(i.text)

In [200]:
IMDB100=pd.DataFrame({})
IMDB100['Name of the show']=Name
IMDB100['Year span']=Span
IMDB100['Genre']=Genre
IMDB100['Runtime']=Runtime
IMDB100['Ratings']=Rating
IMDB100['Votes']=Votes
IMDB100

,Name of the show,Year span,Genre,Runtime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,834,780"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"873,556"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"879,009"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"264,129"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"225,657"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,778"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,384"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"169,475"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,114"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"193,258"

# 10. UCI DATASET

In [28]:
driver=webdriver.Chrome(r"C:\Users\Harshil Goradia\Downloads\chromedriver_win32\chromedriver")
driver.get('https://archive.ics.uci.edu/')

In [34]:
btn=driver.find_elements_by_xpath("//span[@class='whitetext']//a")

In [35]:
for i in btn:
    if i.text=="View ALL Data Sets":
        i.click()
        break

In [36]:
Dataset=[]
Type=[]
Task=[]
Attribute=[]
Instances=[]
No_Attribute=[]
Year=[]

In [44]:
rows= WebDriverWait(driver, 20).until(EC.visibility_of_all_elements_located((By.XPATH, "//table/tbody/tr/td[2]/table[2]/tbody/tr")))
for row in rows:
    Dataset.append(row.find_element_by_xpath('./td[1]').text)
    Type.append(row.find_element_by_xpath('./td[2]').text)
    Task.append(row.find_element_by_xpath('./td[3]').text)
    Attribute.append(row.find_element_by_xpath('./td[4]').text)
    Instances.append(row.find_element_by_xpath('./td[5]').text)
    No_Attribute.append(row.find_element_by_xpath('./td[6]').text)
    Year.append(row.find_element_by_xpath('./td[7]').text)

In [46]:
UCI_dataset=pd.DataFrame({"Dataset Name":Dataset,"Data Type":Type,"Task":Task,"Attribute Type":Attribute,"No of Instances":Instances,"No of Attributes":No_Attribute,"Years":Year})
UCI_dataset=UCI_dataset[2:]

In [47]:
UCI_dataset

,Dataset Name,Data Type,Task,Attribute Type,No of Instances,No of Attributes,Years
2,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
3,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
4,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
5,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
6,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
585,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
586,Gait Classification,Multivariate,Classification,Real,48,321,2020
587,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
588,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
589,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021